apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc-order-foursix
  name: api-svc-order-foursix
spec:
  selector:
    app: foursix-order-deployment
  ports:
  - port: 30020
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
